import { About } from '@/components/About/about'
import { Insertion } from '@/components/Insertion/insertion'
import { Network } from '@/components/Network/network'
import { Skill } from '@/components/Skill/skill'
import { Projects } from '@/components/projects/projects'
import { Container, Parts } from '@/styles/home'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Network />
        <Parts>
          <Insertion />
          <About />
          <Skill />
          <Projects />
        </Parts>
      </Container>
    </>
  )
}
