import { About } from '@/components/About/about'
import { Insertion } from '@/components/Insertion/insertion'
import { Projects } from '@/components/projects/projects'
import { Container } from '@/styles/home'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
          <Insertion/>
          <About />
          <Projects />
      </Container>
    </>
  )
}
